[package]
name = "fox32asm"
version = "0.3.0"
edition = "2021"
build = "build.rs"

[dependencies]
lazy_static = "1.4.0"
pest = "2.1.3"
pest_derive = "2.1.0"

[build-dependencies]
anyhow = "1.0"
vergen = { version = "6", default-features = false, features = ["build", "git"] }
